apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-native-cicd-pipeline
  namespace: tekton-pipelines
spec:
  params:
  - name: git-url
    type: string
  - default: main
    name: git-revision
    type: string
  - name: image-name
    type: string
  - name: image-tag
    type: string
  - default: http://gitea-http.platform.svc.cluster.local:3000/gitea_admin/apps-deploy.git
    name: gitops-repo-url
    type: string
  - default: apps/admin-server/overlays/pre
    name: overlay-path
    type: string
  workspaces:
  - name: shared-data
  - name: maven-settings
  - name: maven-local-repo
    optional: true
  - name: gitops-workspace
  tasks:
  - name: fetch-source
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
  - name: build-native-binary
    runAfter:
    - fetch-source
    taskRef:
      kind: Task
      name: quarkus-native-build
    timeout: 2h0m0s
    workspaces:
    - name: source
      workspace: shared-data
    - name: maven-settings
      workspace: maven-settings
    - name: maven-local-repo
      workspace: maven-local-repo
  - name: build-and-push-image
    params:
    - name: IMAGE
      value: $(params.image-name)
    - name: TAG
      value: $(params.image-tag)
    runAfter:
    - build-native-binary
    taskRef:
      kind: Task
      name: kaniko-build-native
    workspaces:
    - name: source
      workspace: shared-data
  - name: update-gitops-repo
    params:
    - name: gitops-repo-url
      value: $(params.gitops-repo-url)
    - name: image-name
      value: $(params.image-name)
    - name: image-tag
      value: $(params.image-tag)
    - name: overlay-path
      value: $(params.overlay-path)
    runAfter:
    - build-and-push-image
    taskRef:
      kind: Task
      name: update-gitops-repo
    workspaces:
    - name: gitops-source
      workspace: gitops-workspace
