apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: business-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: admin-server-test
        path: apps/admin-server/overlays/test
        destNamespace: quarkus-test
      - appName: admin-server-pre
        path: apps/admin-server/overlays/pre
        destNamespace: quarkus-pre
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: http://gitea-http.platform.svc.cluster.local:3000/gitea_admin/admin-quarkus-jimmer.git
        targetRevision: main
        path: 'gitops/{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
