apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-cicd-pipeline
  namespace: tekton-pipelines
spec:
  params:
  - name: git-url
    type: string
  - default: main
    name: git-revision
    type: string
  - name: image-name
    type: string
  - name: image-tag
    type: string
  - default: gitops/apps/admin-server/overlays/test
    name: overlay-path
    type: string
  workspaces:
  - name: shared-data
  - name: maven-settings
  - name: maven-local-repo
    optional: true
  tasks:
  - name: fetch-source
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
  - name: build-and-push-image
    params:
    - name: IMAGE
      value: $(params.image-name)
    - name: IMAGE_TAG
      value: $(params.image-tag)
    runAfter:
    - fetch-source
    taskRef:
      kind: Task
      name: quarkus-maven-kaniko-push
    workspaces:
    - name: source
      workspace: shared-data
    - name: maven-settings
      workspace: maven-settings
  - name: update-gitops-repo
    params:
    - name: image-name
      value: $(params.image-name)
    - name: image-tag
      value: $(params.image-tag)
    - name: overlay-path
      value: $(params.overlay-path)
    runAfter:
    - build-and-push-image
    taskRef:
      kind: Task
      name: update-gitops-repo
    workspaces:
    - name: source
      workspace: shared-data
