CREATE
SEQUENCE IF NOT EXISTS event_store_id_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_dept_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_dict_data_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_dict_type_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_menu_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_post_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_role_menu_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_role_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_tenant_package_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS event_store_SEQ START WITH 1 INCREMENT BY 50;

CREATE
SEQUENCE IF NOT EXISTS system_tenant_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_user_post_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_user_role_seq START WITH 1 INCREMENT BY 1;

CREATE
SEQUENCE IF NOT EXISTS system_users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE event_store
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregate_type VARCHAR(255)                NOT NULL,
    aggregate_id   VARCHAR(255)                NOT NULL,
    event_type     VARCHAR(255)                NOT NULL,
    version        BIGINT                      NOT NULL,
    event_data     JSONB                       NOT NULL,
    metadata       JSONB,
    occurred_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    stored_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT event_store_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE event_store IS '事件溯源存储表';
COMMENT ON COLUMN event_store.aggregate_type IS '聚合类型（如 User, Role, Order）';
COMMENT ON COLUMN event_store.aggregate_id IS '聚合唯一标识';
COMMENT ON COLUMN event_store.event_type IS '事件类型（如 UserCreated, RoleUpdated）';
COMMENT ON COLUMN event_store.version IS '事件版本号（用于乐观锁和顺序保证）';
COMMENT ON COLUMN event_store.event_data IS '事件数据（JSON格式）';
COMMENT ON COLUMN event_store.metadata IS '事件元数据（traceId, userId, tenantId等）';
COMMENT ON COLUMN event_store.occurred_at IS '事件发生时间';
COMMENT ON COLUMN event_store.stored_at IS '事件存储时间';

CREATE TABLE system_dept
(
    id             BIGINT                      DEFAULT nextval('system_dept_seq') NOT NULL,
    name           VARCHAR(30)                 DEFAULT ''                         NOT NULL,
    parent_id      BIGINT                      DEFAULT 0                          NOT NULL,
    sort           INTEGER                     DEFAULT 0                          NOT NULL,
    leader_user_id BIGINT,
    phone          VARCHAR(11),
    email          VARCHAR(50),
    status         SMALLINT                                                       NOT NULL,
    creator        VARCHAR(64)                 DEFAULT '',
    create_time    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    updater        VARCHAR(64)                 DEFAULT '',
    update_time    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    deleted        SMALLINT                    DEFAULT 0                          NOT NULL,
    tenant_id      BIGINT                      DEFAULT 0                          NOT NULL,
    CONSTRAINT pk_system_dept PRIMARY KEY (id)
);
COMMENT ON TABLE system_dept IS '部门表';
COMMENT ON COLUMN system_dept.id IS '部门id';
COMMENT ON COLUMN system_dept.name IS '部门名称';
COMMENT ON COLUMN system_dept.parent_id IS '父部门id';
COMMENT ON COLUMN system_dept.sort IS '显示顺序';
COMMENT ON COLUMN system_dept.leader_user_id IS '负责人';
COMMENT ON COLUMN system_dept.phone IS '联系电话';
COMMENT ON COLUMN system_dept.email IS '邮箱';
COMMENT ON COLUMN system_dept.status IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN system_dept.creator IS '创建者';
COMMENT ON COLUMN system_dept.create_time IS '创建时间';
COMMENT ON COLUMN system_dept.updater IS '更新者';
COMMENT ON COLUMN system_dept.update_time IS '更新时间';
COMMENT ON COLUMN system_dept.deleted IS '是否删除';
COMMENT ON COLUMN system_dept.tenant_id IS '租户编号';

CREATE TABLE system_dict_data
(
    id          BIGINT                      DEFAULT nextval('system_dict_data_seq') NOT NULL,
    sort        INTEGER                     DEFAULT 0                               NOT NULL,
    label       VARCHAR(100)                DEFAULT ''                              NOT NULL,
    value       VARCHAR(100)                DEFAULT ''                              NOT NULL,
    dict_type   VARCHAR(100)                DEFAULT ''                              NOT NULL,
    status      SMALLINT                    DEFAULT 0                               NOT NULL,
    color_type  VARCHAR(100)                DEFAULT '',
    css_class   VARCHAR(100)                DEFAULT '',
    remark      VARCHAR(500),
    creator     VARCHAR(64)                 DEFAULT '',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    updater     VARCHAR(64)                 DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    deleted     SMALLINT                    DEFAULT 0                               NOT NULL,
    CONSTRAINT pk_system_dict_data PRIMARY KEY (id)
);
COMMENT ON TABLE system_dict_data IS '字典数据表';
COMMENT ON COLUMN system_dict_data.id IS '字典编码';
COMMENT ON COLUMN system_dict_data.sort IS '字典排序';
COMMENT ON COLUMN system_dict_data.label IS '字典标签';
COMMENT ON COLUMN system_dict_data.value IS '字典键值';
COMMENT ON COLUMN system_dict_data.dict_type IS '字典类型';
COMMENT ON COLUMN system_dict_data.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN system_dict_data.color_type IS '颜色类型';
COMMENT ON COLUMN system_dict_data.css_class IS 'css 样式';
COMMENT ON COLUMN system_dict_data.remark IS '备注';
COMMENT ON COLUMN system_dict_data.creator IS '创建者';
COMMENT ON COLUMN system_dict_data.create_time IS '创建时间';
COMMENT ON COLUMN system_dict_data.updater IS '更新者';
COMMENT ON COLUMN system_dict_data.update_time IS '更新时间';
COMMENT ON COLUMN system_dict_data.deleted IS '是否删除';

CREATE TABLE system_dict_type
(
    id           BIGINT                      DEFAULT nextval('system_dict_type_seq') NOT NULL,
    name         VARCHAR(100)                DEFAULT ''                              NOT NULL,
    type         VARCHAR(100)                DEFAULT ''                              NOT NULL,
    status       SMALLINT                    DEFAULT 0                               NOT NULL,
    remark       VARCHAR(500),
    creator      VARCHAR(64)                 DEFAULT '',
    create_time  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    updater      VARCHAR(64)                 DEFAULT '',
    update_time  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    deleted      SMALLINT                    DEFAULT 0                               NOT NULL,
    deleted_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_system_dict_type PRIMARY KEY (id)
);
COMMENT ON TABLE system_dict_type IS '字典类型表';
COMMENT ON COLUMN system_dict_type.id IS '字典主键';
COMMENT ON COLUMN system_dict_type.name IS '字典名称';
COMMENT ON COLUMN system_dict_type.type IS '字典类型';
COMMENT ON COLUMN system_dict_type.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN system_dict_type.remark IS '备注';
COMMENT ON COLUMN system_dict_type.creator IS '创建者';
COMMENT ON COLUMN system_dict_type.create_time IS '创建时间';
COMMENT ON COLUMN system_dict_type.updater IS '更新者';
COMMENT ON COLUMN system_dict_type.update_time IS '更新时间';
COMMENT ON COLUMN system_dict_type.deleted IS '是否删除';
COMMENT ON COLUMN system_dict_type.deleted_time IS '删除时间';

CREATE TABLE system_menu
(
    id             BIGINT                      DEFAULT nextval('system_menu_seq') NOT NULL,
    name           VARCHAR(50)                                                    NOT NULL,
    permission     VARCHAR(100)                DEFAULT ''                         NOT NULL,
    type           SMALLINT                                                       NOT NULL,
    sort           INTEGER                     DEFAULT 0                          NOT NULL,
    parent_id      BIGINT                      DEFAULT 0                          NOT NULL,
    path           VARCHAR(200)                DEFAULT '',
    icon           VARCHAR(100)                DEFAULT '#',
    component      VARCHAR(255),
    component_name VARCHAR(255),
    status         SMALLINT                    DEFAULT 0                          NOT NULL,
    visible        BOOLEAN                     DEFAULT TRUE                       NOT NULL,
    keep_alive     BOOLEAN                     DEFAULT TRUE                       NOT NULL,
    always_show    BOOLEAN                     DEFAULT TRUE                       NOT NULL,
    creator        VARCHAR(64)                 DEFAULT '',
    create_time    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    updater        VARCHAR(64)                 DEFAULT '',
    update_time    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    deleted        SMALLINT                    DEFAULT 0                          NOT NULL,
    CONSTRAINT pk_system_menu PRIMARY KEY (id)
);
COMMENT ON TABLE system_menu IS '菜单权限表';
COMMENT ON COLUMN system_menu.id IS '菜单ID';
COMMENT ON COLUMN system_menu.name IS '菜单名称';
COMMENT ON COLUMN system_menu.permission IS '权限标识';
COMMENT ON COLUMN system_menu.type IS '菜单类型';
COMMENT ON COLUMN system_menu.sort IS '显示顺序';
COMMENT ON COLUMN system_menu.parent_id IS '父菜单ID';
COMMENT ON COLUMN system_menu.path IS '路由地址';
COMMENT ON COLUMN system_menu.icon IS '菜单图标';
COMMENT ON COLUMN system_menu.component IS '组件路径';
COMMENT ON COLUMN system_menu.component_name IS '组件名';
COMMENT ON COLUMN system_menu.status IS '菜单状态';
COMMENT ON COLUMN system_menu.visible IS '是否可见';
COMMENT ON COLUMN system_menu.keep_alive IS '是否缓存';
COMMENT ON COLUMN system_menu.always_show IS '是否总是显示';
COMMENT ON COLUMN system_menu.creator IS '创建者';
COMMENT ON COLUMN system_menu.create_time IS '创建时间';
COMMENT ON COLUMN system_menu.updater IS '更新者';
COMMENT ON COLUMN system_menu.update_time IS '更新时间';
COMMENT ON COLUMN system_menu.deleted IS '是否删除';

CREATE TABLE system_post
(
    id          BIGINT                      DEFAULT nextval('system_post_seq') NOT NULL,
    code        VARCHAR(64)                                                    NOT NULL,
    name        VARCHAR(50)                                                    NOT NULL,
    sort        INTEGER                                                        NOT NULL,
    status      SMALLINT                                                       NOT NULL,
    remark      VARCHAR(500),
    creator     VARCHAR(64)                 DEFAULT '',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    updater     VARCHAR(64)                 DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    deleted     SMALLINT                    DEFAULT 0                          NOT NULL,
    tenant_id   BIGINT                      DEFAULT 0                          NOT NULL,
    CONSTRAINT pk_system_post PRIMARY KEY (id)
);
COMMENT ON TABLE system_post IS '岗位信息表';
COMMENT ON COLUMN system_post.id IS '岗位ID';
COMMENT ON COLUMN system_post.code IS '岗位编码';
COMMENT ON COLUMN system_post.name IS '岗位名称';
COMMENT ON COLUMN system_post.sort IS '显示顺序';
COMMENT ON COLUMN system_post.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN system_post.remark IS '备注';
COMMENT ON COLUMN system_post.creator IS '创建者';
COMMENT ON COLUMN system_post.create_time IS '创建时间';
COMMENT ON COLUMN system_post.updater IS '更新者';
COMMENT ON COLUMN system_post.update_time IS '更新时间';
COMMENT ON COLUMN system_post.deleted IS '是否删除';
COMMENT ON COLUMN system_post.tenant_id IS '租户编号';

CREATE TABLE system_role
(
    id                  BIGINT                      DEFAULT nextval('system_role_seq') NOT NULL,
    name                VARCHAR(30)                                                    NOT NULL,
    code                VARCHAR(100)                                                   NOT NULL,
    sort                INTEGER                                                        NOT NULL,
    data_scope          SMALLINT                    DEFAULT 1                          NOT NULL,
    data_scope_dept_ids VARCHAR(500)                DEFAULT ''                         NOT NULL,
    status              SMALLINT                                                       NOT NULL,
    type                SMALLINT                                                       NOT NULL,
    remark              VARCHAR(500),
    creator             VARCHAR(64)                 DEFAULT '',
    create_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    updater             VARCHAR(64)                 DEFAULT '',
    update_time         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                      NOT NULL,
    deleted             SMALLINT                    DEFAULT 0                          NOT NULL,
    tenant_id           BIGINT                      DEFAULT 0                          NOT NULL,
    CONSTRAINT pk_system_role PRIMARY KEY (id)
);
COMMENT ON TABLE system_role IS '角色信息表';
COMMENT ON COLUMN system_role.id IS '角色ID';
COMMENT ON COLUMN system_role.name IS '角色名称';
COMMENT ON COLUMN system_role.code IS '角色权限字符串';
COMMENT ON COLUMN system_role.sort IS '显示顺序';
COMMENT ON COLUMN system_role.data_scope IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN system_role.data_scope_dept_ids IS '数据范围 ( 指定部门数组)';
COMMENT ON COLUMN system_role.status IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN system_role.type IS '角色类型';
COMMENT ON COLUMN system_role.remark IS '备注';
COMMENT ON COLUMN system_role.creator IS '创建者';
COMMENT ON COLUMN system_role.create_time IS '创建时间';
COMMENT ON COLUMN system_role.updater IS '更新者';
COMMENT ON COLUMN system_role.update_time IS '更新时间';
COMMENT ON COLUMN system_role.deleted IS '是否删除';
COMMENT ON COLUMN system_role.tenant_id IS '租户编号';

CREATE TABLE system_role_menu
(
    id          BIGINT                      DEFAULT nextval('system_role_menu_seq') NOT NULL,
    role_id     BIGINT                                                              NOT NULL,
    menu_id     BIGINT                                                              NOT NULL,
    creator     VARCHAR(64)                 DEFAULT '',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    updater     VARCHAR(64)                 DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    deleted     SMALLINT                    DEFAULT 0                               NOT NULL,
    tenant_id   BIGINT                      DEFAULT 0                               NOT NULL,
    CONSTRAINT pk_system_role_menu PRIMARY KEY (id)
);
COMMENT ON TABLE system_role_menu IS '角色和菜单关联表';
COMMENT ON COLUMN system_role_menu.id IS '自增编号';
COMMENT ON COLUMN system_role_menu.role_id IS '角色ID';
COMMENT ON COLUMN system_role_menu.menu_id IS '菜单ID';
COMMENT ON COLUMN system_role_menu.creator IS '创建者';
COMMENT ON COLUMN system_role_menu.create_time IS '创建时间';
COMMENT ON COLUMN system_role_menu.updater IS '更新者';
COMMENT ON COLUMN system_role_menu.update_time IS '更新时间';
COMMENT ON COLUMN system_role_menu.deleted IS '是否删除';
COMMENT ON COLUMN system_role_menu.tenant_id IS '租户编号';

CREATE TABLE system_tenant
(
    id              BIGINT                      DEFAULT nextval('system_tenant_seq') NOT NULL,
    name            VARCHAR(30)                                                      NOT NULL,
    contact_user_id BIGINT,
    contact_name    VARCHAR(30)                                                      NOT NULL,
    contact_mobile  VARCHAR(500),
    status          SMALLINT                    DEFAULT 0                            NOT NULL,
    websites        VARCHAR(256)                DEFAULT '',
    package_id      BIGINT                                                           NOT NULL,
    expire_time     TIMESTAMP WITHOUT TIME ZONE                                      NOT NULL,
    account_count   INTEGER                                                          NOT NULL,
    creator         VARCHAR(64)                 DEFAULT ''                           NOT NULL,
    create_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                        NOT NULL,
    updater         VARCHAR(64)                 DEFAULT '',
    update_time     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                        NOT NULL,
    deleted         SMALLINT                    DEFAULT 0                            NOT NULL,
    CONSTRAINT pk_system_tenant PRIMARY KEY (id)
);
COMMENT ON TABLE system_tenant IS '租户表';
COMMENT ON COLUMN system_tenant.id IS '租户编号';
COMMENT ON COLUMN system_tenant.name IS '租户名';
COMMENT ON COLUMN system_tenant.contact_user_id IS '联系人的用户编号';
COMMENT ON COLUMN system_tenant.contact_name IS '联系人';
COMMENT ON COLUMN system_tenant.contact_mobile IS '联系手机';
COMMENT ON COLUMN system_tenant.status IS '租户状态（0正常 1停用）';
COMMENT ON COLUMN system_tenant.websites IS '绑定域名数组';
COMMENT ON COLUMN system_tenant.package_id IS '租户套餐编号';
COMMENT ON COLUMN system_tenant.expire_time IS '过期时间';
COMMENT ON COLUMN system_tenant.account_count IS '账号数量';
COMMENT ON COLUMN system_tenant.creator IS '创建者';
COMMENT ON COLUMN system_tenant.create_time IS '创建时间';
COMMENT ON COLUMN system_tenant.updater IS '更新者';
COMMENT ON COLUMN system_tenant.update_time IS '更新时间';
COMMENT ON COLUMN system_tenant.deleted IS '是否删除';

CREATE TABLE system_tenant_package
(
    id          BIGINT                      DEFAULT nextval('system_tenant_package_seq') NOT NULL,
    name        VARCHAR(30)                                                              NOT NULL,
    status      SMALLINT                    DEFAULT 0                                    NOT NULL,
    remark      VARCHAR(256)                DEFAULT '',
    menu_ids    VARCHAR(4096)                                                            NOT NULL,
    creator     VARCHAR(64)                 DEFAULT ''                                   NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                                NOT NULL,
    updater     VARCHAR(64)                 DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                                NOT NULL,
    deleted     SMALLINT                    DEFAULT 0                                    NOT NULL,
    CONSTRAINT pk_system_tenant_package PRIMARY KEY (id)
);
COMMENT ON TABLE system_tenant_package IS '租户套餐表';
COMMENT ON COLUMN system_tenant_package.id IS '套餐编号';
COMMENT ON COLUMN system_tenant_package.name IS '套餐名';
COMMENT ON COLUMN system_tenant_package.status IS '租户状态（0正常 1停用）';
COMMENT ON COLUMN system_tenant_package.remark IS '备注';
COMMENT ON COLUMN system_tenant_package.menu_ids IS '关联的菜单编号';
COMMENT ON COLUMN system_tenant_package.creator IS '创建者';
COMMENT ON COLUMN system_tenant_package.create_time IS '创建时间';
COMMENT ON COLUMN system_tenant_package.updater IS '更新者';
COMMENT ON COLUMN system_tenant_package.update_time IS '更新时间';
COMMENT ON COLUMN system_tenant_package.deleted IS '是否删除';

CREATE TABLE system_user_post
(
    id          BIGINT                      DEFAULT nextval('system_user_post_seq') NOT NULL,
    user_id     BIGINT                      DEFAULT 0                               NOT NULL,
    post_id     BIGINT                      DEFAULT 0                               NOT NULL,
    creator     VARCHAR(64)                 DEFAULT '',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    updater     VARCHAR(64)                 DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                           NOT NULL,
    deleted     SMALLINT                    DEFAULT 0                               NOT NULL,
    tenant_id   BIGINT                      DEFAULT 0                               NOT NULL,
    CONSTRAINT pk_system_user_post PRIMARY KEY (id)
);
COMMENT ON TABLE system_user_post IS '用户岗位表';
COMMENT ON COLUMN system_user_post.id IS 'id';
COMMENT ON COLUMN system_user_post.user_id IS '用户ID';
COMMENT ON COLUMN system_user_post.post_id IS '岗位ID';
COMMENT ON COLUMN system_user_post.creator IS '创建者';
COMMENT ON COLUMN system_user_post.create_time IS '创建时间';
COMMENT ON COLUMN system_user_post.updater IS '更新者';
COMMENT ON COLUMN system_user_post.update_time IS '更新时间';
COMMENT ON COLUMN system_user_post.deleted IS '是否删除';
COMMENT ON COLUMN system_user_post.tenant_id IS '租户编号';

CREATE TABLE system_user_role
(
    id          BIGINT                      DEFAULT nextval('system_user_role_seq') NOT NULL,
    user_id     BIGINT                                                              NOT NULL,
    role_id     BIGINT                                                              NOT NULL,
    creator     VARCHAR(64)                 DEFAULT 'admin',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updater     VARCHAR(64)                 DEFAULT 'admin',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    deleted     SMALLINT                    DEFAULT 0                               NOT NULL,
    tenant_id   BIGINT                      DEFAULT 0                               NOT NULL,
    CONSTRAINT pk_system_user_role PRIMARY KEY (id)
);
COMMENT ON TABLE system_user_role IS '用户和角色关联表';
COMMENT ON COLUMN system_user_role.id IS '自增编号';
COMMENT ON COLUMN system_user_role.user_id IS '用户ID';
COMMENT ON COLUMN system_user_role.role_id IS '角色ID';
COMMENT ON COLUMN system_user_role.creator IS '创建者';
COMMENT ON COLUMN system_user_role.create_time IS '创建时间';
COMMENT ON COLUMN system_user_role.updater IS '更新者';
COMMENT ON COLUMN system_user_role.update_time IS '更新时间';
COMMENT ON COLUMN system_user_role.deleted IS '是否删除';
COMMENT ON COLUMN system_user_role.tenant_id IS '租户编号';

CREATE TABLE system_users
(
    id          BIGINT                      DEFAULT nextval('system_users_seq') NOT NULL,
    username    VARCHAR(30)                                                     NOT NULL,
    password    VARCHAR(100)                DEFAULT ''                          NOT NULL,
    nickname    VARCHAR(30)                                                     NOT NULL,
    remark      VARCHAR(500),
    dept_id     BIGINT,
    post_ids    VARCHAR(255),
    email       VARCHAR(50)                 DEFAULT '',
    mobile      VARCHAR(11)                 DEFAULT '',
    sex         SMALLINT                    DEFAULT 0,
    avatar      VARCHAR(512)                DEFAULT '',
    status      SMALLINT                    DEFAULT 0                           NOT NULL,
    login_ip    VARCHAR(50)                 DEFAULT '',
    login_date  TIMESTAMP WITHOUT TIME ZONE,
    creator     VARCHAR(64)                 DEFAULT '',
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                       NOT NULL,
    updater     VARCHAR(64)                 DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                       NOT NULL,
    deleted     SMALLINT                    DEFAULT 0                           NOT NULL,
    tenant_id   BIGINT                      DEFAULT 0                           NOT NULL,
    CONSTRAINT pk_system_users PRIMARY KEY (id)
);
COMMENT ON TABLE system_users IS '用户信息表';
COMMENT ON COLUMN system_users.id IS '用户ID';
COMMENT ON COLUMN system_users.username IS '用户账号';
COMMENT ON COLUMN system_users.password IS '密码';
COMMENT ON COLUMN system_users.nickname IS '用户昵称';
COMMENT ON COLUMN system_users.remark IS '备注';
COMMENT ON COLUMN system_users.dept_id IS '部门ID';
COMMENT ON COLUMN system_users.post_ids IS '岗位编号数组';
COMMENT ON COLUMN system_users.email IS '用户邮箱';
COMMENT ON COLUMN system_users.mobile IS '手机号码';
COMMENT ON COLUMN system_users.sex IS '用户性别';
COMMENT ON COLUMN system_users.avatar IS '头像地址';
COMMENT ON COLUMN system_users.status IS '帐号状态（0正常 1停用）';
COMMENT ON COLUMN system_users.login_ip IS '最后登录IP';
COMMENT ON COLUMN system_users.login_date IS '最后登录时间';
COMMENT ON COLUMN system_users.creator IS '创建者';
COMMENT ON COLUMN system_users.create_time IS '创建时间';
COMMENT ON COLUMN system_users.updater IS '更新者';
COMMENT ON COLUMN system_users.update_time IS '更新时间';
COMMENT ON COLUMN system_users.deleted IS '是否删除';
COMMENT ON COLUMN system_users.tenant_id IS '租户编号';

ALTER TABLE event_store
    ADD CONSTRAINT event_store_aggregate_type_aggregate_id_version_key UNIQUE (aggregate_type, aggregate_id, version);

CREATE INDEX idx_event_store_aggregate ON event_store (aggregate_type, aggregate_id);

CREATE INDEX idx_event_store_event_type ON event_store (event_type);

CREATE INDEX idx_event_store_occurred_at ON event_store (aggregate_type, occurred_at);
