package io.github.faustofan.admin.shared.distributed.idempotent;

/**
 * 幂等策略枚举
 */
public enum IdempotentStrategy {

    /**
     * 基于Token的幂等
     * <p>
     * 客户端预先获取Token，请求时携带Token进行幂等校验
     */
    TOKEN("Token幂等"),

    /**
     * 基于参数的幂等
     * <p>
     * 根据请求参数（如业务ID、用户ID等）生成幂等Key
     */
    PARAM("参数幂等"),

    /**
     * 基于请求头的幂等
     * <p>
     * 从请求头中获取幂等Key（如 X-Idempotent-Key）
     */
    HEADER("请求头幂等"),

    /**
     * 基于SpEL表达式的幂等
     * <p>
     * 使用SpEL表达式从方法参数中提取幂等Key
     */
    SPEL("SpEL表达式幂等"),

    /**
     * 自动生成幂等Key
     * <p>
     * 根据方法签名和参数自动生成幂等Key
     */
    AUTO("自动生成");

    private final String description;

    IdempotentStrategy(String description) {
        this.description = description;
    }

    /**
     * 获取策略描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 是否需要客户端提供Key
     */
    public boolean requiresClientKey() {
        return this == TOKEN || this == HEADER;
    }

    /**
     * 是否自动生成Key
     */
    public boolean isAutoGenerated() {
        return this == PARAM || this == SPEL || this == AUTO;
    }
}
